#!/bin/bash

echo "Setting up parallel databases for RAILS_ENV=${RAILS_ENV}..."

FAIL=0

echo `whoami`
ls -al tmp
echo "--"

rm -rf /app/pender/tmp/cache /app/pender/tmp/cache1 /app/pender/tmp/cache2 /app/pender/tmp/cache3
mkdir -p /app/pender/tmp/cache /app/pender/tmp/cache1 /app/pender/tmp/cache2 /app/pender/tmp/cache3

echo `pwd`
ls -al tmp
echo `env`
echo "-------------------------------------------------------------------------"

bundle exec rake db:create db:migrate &
TEST_ENV_NUMBER=1 bundle exec rake db:create db:migrate &
TEST_ENV_NUMBER=2 bundle exec rake db:create db:migrate &
TEST_ENV_NUMBER=3 bundle exec rake db:create db:migrate &

for job in `jobs -p`
do
  echo $job
  wait $job || let "FAIL+=1"
done

echo $FAIL

if [ "$FAIL" == "0" ];
then
  exit 0
else
  exit 1
fi
