#!/bin/bash

if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ $TRAVIS_TEST_RESULT == 0 ]]
then
  cd test
  echo 'Format coverage...' && ./cc-test-reporter format-coverage -t simplecov --output ../coverage/codeclimate.json ../coverage/.resultset.json
  echo 'Upload coverage...' && cat ../coverage/codeclimate.json | ./cc-test-reporter upload-coverage --input -
  ./cc-test-reporter show-coverage ../coverage/codeclimate.json
  cd -
fi
