#!/bin/bash

if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ $TRAVIS_TEST_RESULT == 0 ]]
then
  apt-get install -y golang-go golang-glide
  printf '#!/bin/bash\ngo run /tmp/go/src/github.com/codeclimate/test-reporter/main.go $@\n' > test/cc-test-reporter && chmod +x test/cc-test-reporter
  export GOPATH=/tmp/go
  rm -rf /tmp/go/src/github.com/codeclimate
  mkdir -p /tmp/go/src/github.com/codeclimate
  git clone https://github.com/codeclimate/test-reporter /tmp/go/src/github.com/codeclimate/test-reporter
  cd test
  echo 'Format coverage...' && ./cc-test-reporter format-coverage -t simplecov --output ../coverage/codeclimate.json ../coverage/.resultset.json
  echo 'Upload coverage...' && cat ../coverage/codeclimate.json | sed 's/\/app\/app\//app\//g' | ./cc-test-reporter upload-coverage -r $CC_TEST_REPORTER_ID --input -
  ./cc-test-reporter show-coverage ../coverage/codeclimate.json
  cd -
fi
