version: "2"
checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 4
  file-lines:
    enabled: false
  method-lines:
    enabled: false
  method-complexity:
    config:
      threshold: 11
  method-count:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
plugins:
  fixme:
    enabled: false
  rubocop:
    enabled: true
    config: .rubocop.yml
  brakeman:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 19
  bundler-audit:
    enabled: true
exclude_patterns:
- "app/controllers/concerns/*_doc.rb"
- "public/api"
- "lib/tasks"
- "pender-client-php"
- "public/coverage"
- "test"
- "public/javascripts/jquery-2.1.3.min.js"
- "public/javascripts/md5.js"
- "config/environments/*"
