receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: "prometheus"
          scrape_interval: 15s
          static_configs:
            - targets: ["0.0.0.0:3200"] 

processors:
  batch:

exporters:
  otlp/metrics:
    endpoint: "api.honeycomb.io:443" # US instance
    #endpoint: "api.eu1.honeycomb.io:443" # EU instance
    headers:
      "x-honeycomb-team": "<Honeycomb API KEY>"
      "x-honeycomb-dataset": "pender"

service:
  # telemetry:
  #   logs:
  #     level: "debug"
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: []
      exporters: [otlp/metrics]
