module Lapis
  class ErrorCodes
    UNAUTHORIZED = 1
    MISSING_PARAMETERS = 2
    INVALID_VALUE = 4
    UNKNOWN = 5
    DUPLICATED = 9
    TIMEOUT = 10
    API_LIMIT_REACHED = 11
    UNSAFE = 12
    LOGIN_REQUIRED = 13
    NOT_FOUND = 14
    ARCHIVER_HOST_SKIPPED = 20
    ARCHIVER_NOT_FOUND = 21
    ARCHIVER_DISABLED = 22
    ARCHIVER_NOT_SUPPORTED_MEDIA = 23
    ARCHIVER_FAILURE = 24
    ARCHIVER_ERROR = 25
    ARCHIVER_MISSING_KEY = 26
    ARCHIVER_RATE_LIMITED = 28
    ARCHIVER_RETRY_LIMIT_HIT = 29
    PROXY_ERROR = 27
    TEMP_ERRORS = %w(UNKNOWN DUPLICATED TIMEOUT NOT_FOUND)
    ALL = %w(UNAUTHORIZED MISSING_PARAMETERS INVALID_VALUE UNKNOWN DUPLICATED TIMEOUT API_LIMIT_REACHED UNSAFE LOGIN_REQUIRED NOT_FOUND ARCHIVER_HOST_SKIPPED ARCHIVER_NOT_FOUND ARCHIVER_DISABLED ARCHIVER_NOT_SUPPORTED_MEDIA ARCHIVER_FAILURE ARCHIVER_ERROR ARCHIVER_MISSING_KEY PROXY_ERROR)
  end
end
