name: Add Dependabot Reviewer

on:
  pull_request:
    types: [opened, labeled]

jobs:
  add-dependabot-reviewer:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')
    permissions:
      pull-requests: write

    steps:
      - name: Add reviewers for Ruby dependencies
        if: contains(github.event.pull_request.labels.*.name, 'ruby')
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: [' vasconsaurus']
            });
